name: C++ Google Tests CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Установка CMake и компилятора (если нужно)
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      # 3. Сборка проекта
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      # 4. Запуск тестов
      - name: Run Google Tests
        run: |
          cd build
          ctest --output-on-failure
