name: BUILD EXE
on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Установка CMake и компилятора (если нужно)
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      # 3. Сборка проекта
      - name: Build project
        run: |
          cd build
          cmake --build . --config Release

      # 4. Запуск тестов
      - name: Upload EXE artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-executable
          path: build/Release/server.exe

      - name: download EXE artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-executable
          path: ./downloaded

